package com.dugx.event.domain;

import static com.dugx.event.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class BookingDetailAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingDetailAllPropertiesEquals(BookingDetail expected, BookingDetail actual) {
        assertBookingDetailAutoGeneratedPropertiesEquals(expected, actual);
        assertBookingDetailAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingDetailAllUpdatablePropertiesEquals(BookingDetail expected, BookingDetail actual) {
        assertBookingDetailUpdatableFieldsEquals(expected, actual);
        assertBookingDetailUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingDetailAutoGeneratedPropertiesEquals(BookingDetail expected, BookingDetail actual) {
        assertThat(actual)
            .as("Verify BookingDetail auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingDetailUpdatableFieldsEquals(BookingDetail expected, BookingDetail actual) {
        assertThat(actual)
            .as("Verify BookingDetail relevant properties")
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookingDetailUpdatableRelationshipsEquals(BookingDetail expected, BookingDetail actual) {
        assertThat(actual)
            .as("Verify BookingDetail relationships")
            .satisfies(a -> assertThat(a.getBooking()).as("check booking").isEqualTo(expected.getBooking()))
            .satisfies(a -> assertThat(a.getTicketType()).as("check ticketType").isEqualTo(expected.getTicketType()));
    }
}
