package com.dugx.event.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class EventImageAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventImageAllPropertiesEquals(EventImage expected, EventImage actual) {
        assertEventImageAutoGeneratedPropertiesEquals(expected, actual);
        assertEventImageAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventImageAllUpdatablePropertiesEquals(EventImage expected, EventImage actual) {
        assertEventImageUpdatableFieldsEquals(expected, actual);
        assertEventImageUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventImageAutoGeneratedPropertiesEquals(EventImage expected, EventImage actual) {
        assertThat(actual)
            .as("Verify EventImage auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventImageUpdatableFieldsEquals(EventImage expected, EventImage actual) {
        assertThat(actual)
            .as("Verify EventImage relevant properties")
            .satisfies(a -> assertThat(a.getImageUrl()).as("check imageUrl").isEqualTo(expected.getImageUrl()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertEventImageUpdatableRelationshipsEquals(EventImage expected, EventImage actual) {
        assertThat(actual)
            .as("Verify EventImage relationships")
            .satisfies(a -> assertThat(a.getEvent()).as("check event").isEqualTo(expected.getEvent()));
    }
}
