package com.dugx.event.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class OrganizerAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizerAllPropertiesEquals(Organizer expected, Organizer actual) {
        assertOrganizerAutoGeneratedPropertiesEquals(expected, actual);
        assertOrganizerAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizerAllUpdatablePropertiesEquals(Organizer expected, Organizer actual) {
        assertOrganizerUpdatableFieldsEquals(expected, actual);
        assertOrganizerUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizerAutoGeneratedPropertiesEquals(Organizer expected, Organizer actual) {
        assertThat(actual)
            .as("Verify Organizer auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizerUpdatableFieldsEquals(Organizer expected, Organizer actual) {
        assertThat(actual)
            .as("Verify Organizer relevant properties")
            .satisfies(a -> assertThat(a.getCompanyName()).as("check companyName").isEqualTo(expected.getCompanyName()))
            .satisfies(a -> assertThat(a.getTaxCode()).as("check taxCode").isEqualTo(expected.getTaxCode()))
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getVerified()).as("check verified").isEqualTo(expected.getVerified()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertOrganizerUpdatableRelationshipsEquals(Organizer expected, Organizer actual) {
        // empty method
    }
}
