package com.dugx.event.domain;

import static com.dugx.event.domain.AssertUtils.bigDecimalCompareTo;
import static org.assertj.core.api.Assertions.assertThat;

public class TicketTypeAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketTypeAllPropertiesEquals(TicketType expected, TicketType actual) {
        assertTicketTypeAutoGeneratedPropertiesEquals(expected, actual);
        assertTicketTypeAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketTypeAllUpdatablePropertiesEquals(TicketType expected, TicketType actual) {
        assertTicketTypeUpdatableFieldsEquals(expected, actual);
        assertTicketTypeUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketTypeAutoGeneratedPropertiesEquals(TicketType expected, TicketType actual) {
        assertThat(actual)
            .as("Verify TicketType auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketTypeUpdatableFieldsEquals(TicketType expected, TicketType actual) {
        assertThat(actual)
            .as("Verify TicketType relevant properties")
            .satisfies(a -> assertThat(a.getName()).as("check name").isEqualTo(expected.getName()))
            .satisfies(a -> assertThat(a.getPrice()).as("check price").usingComparator(bigDecimalCompareTo).isEqualTo(expected.getPrice()))
            .satisfies(a -> assertThat(a.getQuantity()).as("check quantity").isEqualTo(expected.getQuantity()))
            .satisfies(a -> assertThat(a.getRemaining()).as("check remaining").isEqualTo(expected.getRemaining()))
            .satisfies(a -> assertThat(a.getSaleStart()).as("check saleStart").isEqualTo(expected.getSaleStart()))
            .satisfies(a -> assertThat(a.getSaleEnd()).as("check saleEnd").isEqualTo(expected.getSaleEnd()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertTicketTypeUpdatableRelationshipsEquals(TicketType expected, TicketType actual) {
        assertThat(actual)
            .as("Verify TicketType relationships")
            .satisfies(a -> assertThat(a.getEvent()).as("check event").isEqualTo(expected.getEvent()));
    }
}
